# Generated by Django 5.0.6 on 2026-06-20 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('is_smoke_free', models.BooleanField(verbose_name='پاک بوده؟')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت اختیاری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ثبت روزانه',
                'verbose_name_plural': 'ثبت\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StreakSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='استریک فعلی (روز)')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='بیشترین استریک')),
                ('total_smoke_free_days', models.PositiveIntegerField(default=0, verbose_name='کل روزهای پاکی')),
                ('total_money_saved', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='کل پول پس\u200cانداز شده (تومان)')),
                ('last_relapse_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین لغزش')),
                ('last_checkin_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خلاصه استریک',
                'verbose_name_plural': 'خلاصه استریک\u200cها',
            },
        ),
    ]
