# Generated by Django 5.0.6 on 2026-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلا خرید موتور هوندا', max_length=200, verbose_name='عنوان هدف')),
                ('target_amount_toman', models.PositiveBigIntegerField(verbose_name='هزینه\u200cی هدف (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='هدف فعال (اصلی)؟')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='رسیده به هدف؟')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رسیدن به هدف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'هدف مالی',
                'verbose_name_plural': 'هدف\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
